### PR TITLE
Fix attempt - Always functional profile menu button

### PR DESCRIPTION
**Pull request by keikari**
Removes loading state from profile menu button. This prevented opening of profile menu when `channel_list` didn't return or was slow. 
Moved the logic to channel selector, so it shows some indication for channel list still loading.

NEW | OLD
new-old

### CODE REVIEW

**Comment by tzarebczan** [comment]
Thanks for taking a stab at this!

**Review by infinite-persistence — COMMENTED** [review]
:small_blue_diamond:  Nice. In terms of component structure, it's good to go :+1: 

----

:small_orange_diamond:   Some behavioral things to think about, though:
1. Should the menu button be disabled instead of clickable?  
    - image
2. This will affect every channel-selector usage.  I don't think there is a problem, but just a reminder to check.  e.g. Similar to the first point, should the aesthetic here be showing a disabled/spinning button, rather than a clickable one?
    - image

----

Minor thing:  the git setup is incomplete

image
    
```
git config --global user.name "Name"
git config --global user.email "MY_NAME@example.com"
```

**Comment by infinite-persistence** [comment]
If we want to constraint the new behavior to just the header and not affect other usages, we do can the following. The gray-out and testing concerns would then go away.  

But either method is fine.

image

**Comment by keikari** [comment]
I think generally people should only see the "Loading channels..." text, if there is some issue on SDK making `channel_list` not work.  So no one should ever see it on normal use. 
And think it should be in the channel selector, so users who have problems with `channel_list`, won't bee seeing "Anonymous" as the only option there and think their channel got deleted/filtered or something.  

Made the button disabled when `pendingChannelFetch`.
The adding of spinner wasn't instantly obvious for me for how to make, and since no one should see this, don't feel too bad of current version.(?)

**Review by infinite-persistence — APPROVED** [review]
:+1:

**Comment by tzarebczan** [comment]
@toshokanneko can you check if this needs any adjustments after your PR?

**Pull request merged**
