### PR TITLE
Publish-related issues

### LINKED ISSUE #2510: "Publish Something"-button on "claim not found"-page doesn't do anything
https://odysee.com/asdasadasdadasda

Same with "Claim this handle"-button here
https://odysee.com/@asdasadasdadasda

### LINKED ISSUE #2722: Don't allow clicking "Upload" if no file is selected
1. Select a file to upload
2. Reload page
3. File gets un-selected, but can still try to create an upload. (Results to an error, but still creates an entry in uploads)

### LINKED ISSUE #2801: scheduled stream replay upload issues
- [x]  I think we used to default to "choose replay" option if they have replays (and the current time is after the scheduled time for scheduled ones...for anytime, maybe update only is fine...) ? 
- [x] Since it's on update only, there's a future date filled in. When you use the upload replay option (not select from replays), it keeps the date and the form says "Cannot set to a future date.". Using replay seems to clear it, so we should do the same here. 
    - <sub>Closed by #2816</sub>

### LINKED ISSUE #2842: Publish form: URL doesn't get auto filled on file selection
https://discord.com/channels/721806979928162404/1112809634860908595/1112809634860908595

### PR DESCRIPTION
**Pull request by infinite-persistence**
## Issues Fixed
- Closes #2801
- Fix Preview potentially not showing the actual `release_time` (it should now match the actual payload).
- Clamp `release_time` to `Now` if a replay is uploaded ahead of schedule (odd scenario to allow, but no way around that I guess, since we allow placeholders to be re-used and scheduled moved around).
- Closes #2510
- Closes #2722
- Fix `name` not being cleared when "Clear" is hit.
- #1648: Lower default bid from 0.01 to 0.001
- Fix grayed out inconsistency.  I've also felt that graying out makes it messy, so trying out a simplified look.  Can revert if people dislike.
    - image
- Fix `remote_url` being incorrectly sent when in "Update Only".
- Closes #2842 
- Disable livestream form when "Upload" is selected but no file selected yet.

## Code maintence
Various cleanup of non-functional code from copy/pasting.
The diffs look like a lot, but individual commits should still be clear.

### CODE REVIEW

**Comment by infinite-persistence** [comment]
@keikari, if you have time, do you mind giving Publish Forms a general testing at `kp` (build should be ready in a bit)?

**Comment by keikari** [comment]
* [ ] Long deposit amount format

long-deposit

----
These are old, should I file separately?
* [ ] Inconsistent gray-out with price/restricted content fields
* [ ] Selecting replay in stream edit, but then deciding to just update the stream info instead, will remember the selection and still upload the replay. 
  1. Edit stream 
  2. Choose "Use Replay"  and select one
  3. Select  "Update only" and Save changes
  4. Replay gets uploaded

price-gray-out-kp

**Comment by infinite-persistence** [comment]
> _These are old, should I file separately?_

Here is fine, can try to address them too.  Thanks :+1:

**Comment by keikari** [comment]
* [ ] "Claim this handle" in here should direct to channel creation (directs to file upload at the moment)
https://kp.odysee.tv/@channel-aasdadsasdaddas

Though wondering are these buttons on content/channel-not-found pages used at all by anyone

**Comment by infinite-persistence** [comment]
## Incremental
- Fix bid formatting
- 1648: Lower default bid from 0.01 to 0.001
- Fix grayed out inconsistency.  I've also felt that graying out makes it messy, so trying out a simplified look.  Can revert if people dislike.

image

**Comment by infinite-persistence** [comment]
## Incremental
- Fix `remote_url` being incorrectly sent for "Update Only".

This change would need a re-test.  But let's wait until Jessop reviews it first.
(although it's available on the test instance to try if want to do that earlier).

**Review by jessopb — APPROVED** [review]
Really nice work.

**Comment by infinite-persistence** [comment]
> _This change would need a re-test. But let's wait until Jessop reviews it first. (although it's available on the test instance to try if want to do that earlier)._

I reverted that last commit to not invalidate Miko's testing.  I leave that in `livestream.state.redo` for future reference if needed

I'll redo the `remote_url` fix in a bit later using existing (just bear with obscure variables for now).

**Comment by infinite-persistence** [comment]
Sorry, I reversed the reversal.  Tried the minimal-change approach but couldn't get it right -- the states just don't mean what they say.

Just bite the bullet and do more testing (build will be ready in a few minutes).  There is still a bunch of tickets that would benefit from it anyway.

**Comment by infinite-persistence** [comment]
- Fix "Replay" value in the preview dialog (more changes to be close to 1:1 with the actual payload).
- When there are no replays available but "Use Replay" is selected, the form was originally meant to be grayed out entirely, but broken due to typos and stuff. Restored that logic.

**Comment by infinite-persistence** [comment]
- Fix blinking "format" warning when selecting a file to upload.
- Disable livestream form when "Upload" is selected but no file selected yet.

**Comment by infinite-persistence** [comment]
Closes #2842.

@keikari, give it one last test on `kp` (in 8 minutes), then we push it to address the Discord user's problem?
(_Can be next week too, I know you're busy testing Neko_)

**Comment by keikari** [comment]
Did few more different kinds of uploads and some edits, and things seem to work fine.

**Comment by infinite-persistence** [comment]
Good to go

**Pull request merged**
