### PR TITLE
ClaimPreview & sidebar: strip '@' since channel is implied

### PR DESCRIPTION
**Pull request by infinite-persistence**
## Ticket
Closes [#865: Hide @ symbol in areas where channel names are implied](https://github.com/OdyseeTeam/odysee-frontend/issues/865)

Will probably take some time to get used to it for old timers.

### CODE REVIEW

**Comment by tzarebczan** [comment]
Does this pretty much cover all areas outside of the address bar? Wonder if there's any areas we should still keep, will poke around.

**Comment by infinite-persistence** [comment]
Yeah, pretty much every place that consists of the "avatar, channel title, channel handle" trio, it will strip away.
I thought that implies a channel, but re-reading the ticket, seems like we want to take context into consideration too?

**Comment by tzarebczan** [comment]
No, I think this is the right track. Will get it loaded up today and confirm with Julian.

**Comment by tzarebczan** [comment]
Will ship tomorrow when I have time to monitor feedback. Thank you!

**Pull request merged**
