### PR TITLE
Sidebar: show "last active subs" instead of "by name"

### LINKED ISSUE #1003: Show channels with most recent content on sidebar (and option on following manage page?)
KP mentioned a good idea for the sidebar where we show channels - instead of showing first 10, show based on lastest publish activity. 

This should be possible with a claim search + sort by release time + claims_in_channel = 1. Then grab all the signing channels in the order they appear.

This would be a nice option for the following manage page (leave default + add "recently uploaded"). What's tricky here is that it probably won't work for anything outside of the first 50 (assuming page size 50) results, cause page 2 will repeat again. This is a known limitation on the SDK.

### PR DESCRIPTION
**Pull request by infinite-persistence**
Closes #1003, test @ `kp`

- Show by recent activity instead of alphabetical order.
- Added a section in Following-Manage Page for that too.

"Recently Active" makes sense?  Or "New Activity", or "Updated Channels"?

image

image

### CODE REVIEW

**Comment by infinite-persistence** [comment]
- [ ] When the `claim_search` stalls, the _Recently Active_ section becomes empty, but the title is visible. Probably should just hide it.

**Comment by infinite-persistence** [comment]
Ah crap ... this happens on odd number of subs

image

**Comment by infinite-persistence** [comment]
**Fixes**
- Only show "Recently Updated" if the total subs are more than 10, otherwise it's just a duplicate list. 
- When following/unfollowing from Manage Page, the sidebar and "Recently Update" will not update immediately, to prevent things from jumping around due to list-size changes.  When you navigate to your next destination, these components will resume update.

**Comment by tzarebczan** [comment]
This is looking great! The recently active section could use bigger tiles on desktop, but we can fix that later. This is a big improvements already.

**Pull request merged**
