### PR TITLE
Update eslint

### PR DESCRIPTION
**Pull request by mayeaux**
Upgrades eslint to 7.5 to allow for optional chaining support

### CODE REVIEW

**Comment by mayeaux** [comment]
Seems most of these changes are from `always-multiline` targeting functions, which we probably don't need. 

It can be controlled in a more granular fashion: https://eslint.org/docs/rules/comma-dangle

**Comment by tzarebczan** [comment]
I'd disable that, let's not touch all those files.

**Comment by infinite-persistence** [comment]
Questions:
- I thought optional chaining was already enabled?
- I assume we didn't go all the way to Version 8 because of our current version of Node?

Suggested path (@tzarebczan to decide):
- If the chaining usages are small, perhaps temporarily disable checking those lines for now?  There is already a PR to upgrade Node, so might as well do that first + upgrade to eslint 8 together, so we save extra effort in re-upgrading and re-testing.  

Suggested todo if still want to proceed:
- Quite a number of packages updated, so probably need to set up a dev instance to try out various random things.
- Since we are updating packages and will be testing, we should de-dup some of them. For example, `acorn@^7.1.1:` and `acorn@^7.4.0:` can be unlocked and merged, instead of using both.

**Comment by mayeaux** [comment]
Optional chaining is supported by Node but support for eslint recognizing optional chaining doesn't land until 7.5 

Screen Shot 2022-06-02 at 5 41 25 PM

Can confirm that 7.5 supports the syntax listed above.

Also, flow supports optional chaining by version `v0.112.0` but I checked and there's quite a lot of differences between our current version  and 0.112

I could just ignore the errors but it gets a bit messy to ignore with flow and eslint simultaneously:

```
// $FlowIssue
window.player?.controlBar?.getChild('ChaptersButton')?.hide() // eslint-disable-line no-unused-expressions
```

I think to use this upgrade would keep the code a lot cleaner and be a good mid-way solution

**Comment by tzarebczan** [comment]
Plan is to ship on Monday and try to fix up the dupes in meantime

**Comment by mayeaux** [comment]
Screen Shot 2022-06-03 at 4 01 01 PM
Screen Shot 2022-06-03 at 3 58 56 PM

@infinite-persistence these were the only two that I spotted that were duplicated did you see any others?

**Pull request closed without merging**
