### PR TITLE
Video: add original (non-transcoded) quality selection

### PR DESCRIPTION
**Pull request by infinite-persistence**
Ticket: #638
Test: `kp`

## Behavioral changes
- Added `Original - xxxp` selection;  replaces the same transcoded quality if there is overlap.
- "Auto" - if the algo-selected quality matches the original quality, use the non-transcoded url.

## Future
- [ ] The transition between VHS and non-VHS could be smoother.  Maybe the `preload=false` thing might help (haven't looked).
- [ ] <strike>Not sure how to detect `faststart` before allowing the `Original` selection.
  - Probably something that needs to come from the header fetch?  Even on full fetched video, I'm not sure how to determine if it's `faststart` (not seeing anything ... is it just the sequence of headers?).</strike>
- [ ] Remove the "re-select" hack when "persistent quality setting" is available (see comments in code).

### CODE REVIEW

**Comment by infinite-persistence** [comment]
## Todo
- [ ] Include both transcoded and original in the selection, even if they overlap

**Comment by tzarebczan** [comment]
This is working great!

**Comment by infinite-persistence** [comment]
[ba9d1f9 ](https://github.com/OdyseeTeam/odysee-frontend/commit/ba9d1f9be204cd1129bacd57376e99e8ac1955d1)to [104cc42 ](https://github.com/OdyseeTeam/odysee-frontend/commit/104cc42882255e508d36cf3e3513982729a6a8c2)
- Show _Optimized_ selection despite same height as _Original_.
- Disable background switching from "Auto=Optimized to Original"
- Rebased
- Rebuild `kp`

**Comment by infinite-persistence** [comment]
[104cc42 ](https://github.com/OdyseeTeam/odysee-frontend/commit/104cc42882255e508d36cf3e3513982729a6a8c2)to [2ee75ef ](https://github.com/OdyseeTeam/odysee-frontend/commit/2ee75ef744651f53e48d8f8c56fbfcfcc513b899)
- Fix long/short-form handling of the "Original" button.
  - For mobile, the space is fixed and happened to fit "Original", so using full text. But a string entry is still created for other languages.
- Don't include "Original" for livestreams.
- Rebuilding `kp`...

**Comment by tzarebczan** [comment]
Sweet!

**Pull request merged**
