### PR TITLE
Lazy-load comment components

### PR DESCRIPTION
**Pull request by infinite-persistence**
## Why
~300KB savings in `ui.js` size (production, uncompressed). Mostly coming from the emoji library.

### CODE REVIEW

**Comment by infinite-persistence** [comment]
`--- Set to Draft ---`
Every time the comment components are loaded, the rounded edges are reduced to old lbry.tv radius.

I think it's due to the following code loading lbry.tv variables instead of `themes/odysee/init/vars`.  Not sure why it managed to resolve to the Odysee theme prior to code-splitting.
https://github.com/OdyseeTeam/odysee-frontend/blob/master/ui/scss/component/_comment-create.scss#L1

**Comment by infinite-persistence** [comment]
`--- Ready for review ---`

67eb3d5 to 6035e59
- The lbry.tv theme issue was resolved, so rebase to master. It wasn't actually blocked by it, but just wanted to isolate things.  One thing at a time.

**Before:** ui.js 4.20MB uncompressed --- **After:** ui.js 3.89MB uncompressed

**Comment by infinite-persistence** [comment]
@saltrafael, can you help to review in case I broke something with emojis/stickers?

**Review by saltrafael — APPROVED** [review]
👍🏻  doesnt seem to affect/break anything

**Pull request merged**
