### PR TITLE
Yarn v2 Upgrade

### PR DESCRIPTION
**Pull request by iamflorencejay**
## Other information
Updated yarn version to v2 (berry).

## PR Checklist

<details><summary>Toggle...</summary>

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [x] Other - Please describe:

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

</details>

### CODE REVIEW

**Comment by tzarebczan** [comment]
What are the benefits and implications of upgrading? 

We still have another big upgrade pr that we haven't pushed yet due to potential breaking changes.

**Comment by iamflorencejay** [comment]
> What are the benefits and implications of upgrading?
> 
> We still have another big upgrade pr that we haven't pushed yet due to potential breaking changes.

@tzarebczan check the full changelog:
https://dev.to/arcanis/introducing-yarn-2-4eh1

**Comment by iamflorencejay** [comment]
hmm checking

**Comment by iamflorencejay** [comment]
I will also test the dev server first also

**Pull request closed without merging**
