### PR TITLE
Improve local tab syncing

### LINKED ISSUE #2037: Investigate `redux-state-sync` to address tab sync problems
Preference-syncing is an open issue that we all know. 
Having multiple tabs open is one of the problematic scenarios, where the tab-focus method might not be fast enough since it ends up doing an API call round-trip.

https://github.com/AOHUA/redux-state-sync might be a solution to eliminate the API calls for the tab-to-tab (same PC) case.

### PR DESCRIPTION
**Pull request by infinite-persistence**
## Status
:yellow_circle: Needs more testing @ `kp`

## Issue
- Closes #2037

## Overview
- Changes to synced settings like theme and private playlists are now immediate between local tabs.  This reduces any sync error from the existing API-based mechanism, which doesn't kick in until 2s after the tab is focused, potentially causing merge conflicts.
- The current API-based syncing remain as-is. The idea is that if the changes are done across all tabs, the API-calls will end up being a no-op
    - Edit: will also try to see if we can reduce the calls

## Test
- All settings that are currently saved to the wallet should be tab-synced.
- Additions so far:  
    - Deleting a notification
    - Player seekbar position (already there previously, but re-implemented the new way).
    - _...can add more if you guys find any useful ones_
- Ensure per-tab settings like navigation paths and form values (e.g. comments) are not being overwritten by changes in another tab.
    - Test out as many settings as possible.
        - Publishing? SDK calls?
- Ensure the existing wallet sync between devices isn't broken.
- Note that the following will remain per-tab:
    - Queue (just like other sites)

### CODE REVIEW

**Comment by infinite-persistence** [comment]
- [ ] In Firefox, the page fails to load if the highest security setting (no cookies) is selected. In production, it at least loads but with a bunch of warnings.

**Comment by infinite-persistence** [comment]
- [ ] Handle Miko's findings.
- [ ] Synchronize tab sign-in/sign-out to address the unintended merge problem.

**Comment by infinite-persistence** [comment]
`-- ready for review/push ---`
- `fix` Handle no-storage-permission scenario.
- `new` Force other tabs to immediately reload when 1 tab signs in.
- `postpone` "Incorrect playback rate corner-case" -- will circle back later.
    - Related to the "reset back to 1" scenario mentioned in https://github.com/lbryio/lbry-desktop/pull/5535.  It feels like the single-player version changed the sequence of things.

**Comment by tzarebczan** [comment]
Will give it a whirl today and plan to ship Monday!

Thank you KP, hopefully this nails down the last of our data loss issues.

**Pull request merged**
