### PR TITLE
localStorage + language fixes

### PR DESCRIPTION
**Pull request by infinite-persistence**
## Tickets
Closes [#921 language refresh / selection issues](https://github.com/OdyseeTeam/odysee-frontend/issues/921) -- including the localStorage problems mentioned.

## Changes
- See commit messages for walkthrough.
- :warning: The last commit involves a behavioral change. I think it's for the better, but we can omit it if majority dislikes.

### CODE REVIEW

**Comment by infinite-persistence** [comment]
@saltrafael, can you take a look/test, especially to see if it impacts Nag-Locale, etc.  Memberships remain a priority of course.

**Comment by tzarebczan** [comment]
Confused a bit about the last commit - does it no longer try to use browser language? 

I think the way we wanted it to work was to use browser language if you never had a language set. Once you have one set, keep that unless overwritten by settings change.

**Comment by tzarebczan** [comment]
It broke in not logged in state- 




Please wait a bit, we are still getting your account ready.

**Comment by keikari** [comment]
Some odd auto toggling can happen, something like this(doesn't work every time):
1. Have more than one tabs open
2. Go to settings in tab A
3. Reload either tab (or change focus to tab B and back, seemed also make it happen sometimes)
4. Change language in A
5. Language toggles back and forth(I think it sometimes stopped to previous state.)

(Not sure if the changing focus part happened while this was merged, noticed it after revert)

https://user-images.githubusercontent.com/34790748/188701472-a91b85e4-bf64-4339-bfb4-1ea2691aea9d.mp4

**Pull request merged**
