### PR TITLE
Don't try and show Vidcrunch ad outside US

### PR DESCRIPTION
**Pull request by mayeaux**
Vidcrunch ads are not being filled outside the US but are significantly impacting the UX of the app
Screen Shot 2022-05-16 at 12 54 16 PM
Screen Shot 2022-05-16 at 12 54 03 PM

This stops the sticky ad from impacting the UX outside of the US as a first step

### CODE REVIEW

**Comment by tzarebczan** [comment]
Maybe exclude EU instead? Most of it is in the US,but does work in some other areas too.

**Comment by tzarebczan** [comment]
Poked the new ad provider again this morning btw..

**Comment by infinite-persistence** [comment]
Is that bad floater in old code, or in today's prod? (seeing that the screenshot is localhost)
Pretty sure I tested the fix on iOS.

**Comment by mayeaux** [comment]
Sorry that branch had master from the beginning of last week pulled in but not since then, it seems the floating is fixed now. @infinite-persistence

**Pull request closed without merging**
