### PR TITLE
Support resume-able upload via tus

### PR DESCRIPTION
**Pull request by infinite-persistence**
## 🟢 Status 🟢
App-side done.  Remaining tasks:
- [x] Backend:  handle race issue with `notify`
- [x] Re-test (since many things have changed).  Get Miko to help uncover corner-cases? 
- [ ] Update production env: increase limit to 10GB
- [ ] Add production env with addtional v2 endpoint
- [ ] Push

## PR

<details>
  <summary>Details...</summary>
## Notes
Need help to test more scenarios (e.g. different browsers, different file types, various disconnection scenarios, etc.)

Found and fixed one claim-info error in the backend.  Been comparing the claim output between v1 and v2 endpoints -- looks ok to me now, but I might miss something in the process.

## Test
`KP` test instance

## Ticket
Closes [#38 Handle resumable file upload](https://github.com/OdyseeTeam/odysee-frontend/issues/38)

## Known Issues
- [Minor] The upload stalls for ~10s in the backend for every 100MB, then resumes.  Randy is aware.

</details>

### CODE REVIEW

**Comment by tzarebczan** [comment]
Working really well! Do we control the 100mb chunks, or does the backend ? Might be good to bring that down if we can get the stalling thing fixed. 

Provided some app crashes via Slack. Otherwise should be good to go tomorrow!

**Comment by infinite-persistence** [comment]
We control the chunk size, but lowering it doesn't proportionally lower the stall time at the backend, it seems. I tried something like 1M, 5MB, 10MB, 50MB ... and they all hover around 5s each, which is even worse now because we have more chunks.  Will ask Randy.

**Comment by infinite-persistence** [comment]
238021e to 1eb21a9
- Fix file selector for Firefox Android complaining that the file is different. 
    - Android seems to modify the timestamp (on selection?), so just exclude timestamp in the fingerprint for now.
- Fix "Suspense" crash
    - A dormant bug from code-splitting
- Improved mobile layout a bit.

**Comment by infinite-persistence** [comment]
1eb21a9 to 55e7bc8
- Put back `v1` code to support livestream replays.  While at it, also use v1 for:
    - obsolete browsers (previously, it just stops the upload with an error message)
    - publish previews (since the payload is small)

----

Remaining work:
- [ ] Backend:  handle race issue with `notify`
- [ ] Re-test (since many things have changed).  Get Miko to help uncover corner-cases? 
- [ ] Update production env: increase limit to 10GB
- [ ] Update production env with addtional v2 endpoint
- [ ] Push

**Comment by tzarebczan** [comment]
Still working out a few kinks from testing. Miko also got a duplicate claim to happen once when refreshed, but hasn't been able to repro. 

We may need to auto retry based on certain backend errors if the BE can't do it.

**Comment by infinite-persistence** [comment]
Retry is possible on client side, I think.  I currently just re-try from a "handle intermittent connection problems" standpoint, so only tried 3 attempts in short succession.  Can adjust.

```
      retryDelays: [0, 3000, 3000],

      onShouldRetry: (err, retryAttempt, options) => {
        window.store.dispatch(doUpdateUploadProgress({ params, status: 'retry' }));
        const FORBIDDEN_ERROR = 403;
        const status = err.originalResponse ? err.originalResponse.getStatus() : 0;
        return status !== FORBIDDEN_ERROR;
      },
```

**Comment by keikari** [comment]
Somethings noticed:

**Editing publish clears old resumable uploads from pending uploads list.**

  1. Start upload, and don't let it finish.
  2. Edit some publish(post or file) and submit upload.
  3. First upload disappears from UI. (If it was active, it was still going in the background, based on network traffic)
  
  Doesn't happen with completely new publishes.

--------------------------------------------------
**"Success" pop-up doesn't show if upload is retried**

For pop-up.
   1. Start uploading a small file
   2. Wait it to finish and you get pop-up

Other scenario for no pop-up
   1. Start uploading a small file
   2.  Reload page and retry
   3. Wait it to finish and no pop-up

**Comment by infinite-persistence** [comment]
Thanks @keikari!  The detailed description really made it easy to debug.

ac8ace9 to cc1a5f8
- Fixed missing popup.
- Fixed pending uploads cleared when editing another claim.

**Pull request merged**
