### PR TITLE
Fix null property access bug

### PR DESCRIPTION
**Pull request by david0178418**
Fixes https://github.com/OdyseeTeam/odysee-frontend/issues/747

The app was crashing due to `fetchedReplies` being null.  Optional chaining the length prop resolves this.

### CODE REVIEW

**Review by infinite-persistence — CHANGES_REQUESTED** [review]
This fixes the crash but it is incomplete. It leaves a perpetual spinner after deletion.

image

**Comment by tzarebczan** [comment]
Thanks @david0178418 and @infinite-persistence ! 

David, would you wanna take another shot to see if you can fix that up? What's the case in which this happens?

**Comment by david0178418** [comment]
@infinite-persistence good catch.

This might require a bit more context to determine how this should work.  Here is the current condition:

commentReplies/view.jsx
image

`canDisplayComments` is currently false because there are no comments to display, causing the spinner to be shown.  I'm wondering how this jives with `isResolvingReplies`.  I haven't had a chance to trace these to the props being handed in yet so I'm not entirely certain on the usage yet, but based on solely the variable names, my first guess would be that the spinner should only show if we're "fetching by parent" or "resolving replies".

Is this correct?  Should this condition be `(isFetchingByParentId[parentId] || isResolvingReplies)`?

**Comment by david0178418** [comment]
Also, I should note the question above is just if you happen to know this off the top of your head. If not, then I'll be able to dig in more and find this out in the next couple of days.

**Comment by infinite-persistence** [comment]
@saltrafael might be able to provide context, since he's active in this area.

**Comment by saltrafael** [comment]
I think those changes are back from batch resolve-all before showing and in the case of having no comments to display `fetchedReplies` should return an empty array instead of `null`, then the `canDisplayComments` comparison would return true (which could be improved to make more sense than `canDisplayComments = true` for no comments)

**Comment by david0178418** [comment]
@saltrafael Thanks for the tip.  Going into the selector and simply returning `[]` instead of `null` alone fixes the both the crash and the perpetual spinner.

**Pull request merged**
