### PR TITLE
Language fixes follow-up

### PR DESCRIPTION
**Pull request by infinite-persistence**
See commit messages for rationale.

<sub>Reference(s) mentioned:</sub> <sub>https://sentry.lbry.tech/organizations/odysee/issues/29442/tags/?project=2</sub>

### CODE REVIEW

**Comment by infinite-persistence** [comment]
@miko, @saltrafael, can you give this a quick test/review? 

The build on `kp` will be done in about 8 minutes (check the "changelog" button on the upper-left of the site to confirm)

**Comment by keikari** [comment]
Seems to work well. 
Somethings but guessing these are rare in normal use.

* [ ] If browser language is different than wallet language and not English, language changes twice on log in: browser language -> English -> wallet language

* [ ] The language toggling back and forth can happen with multiple tabs  
1. Have 2 tabs open(only one will be used actively)
2. In tab A go to settings and change language
3. Tab A will do pref_get/set calls
4. After few seconds tab B will also do pref_set call
5. When language is changed again in tab A, there happens pref_get call that instantly toggles language to the previous state set in B

https://user-images.githubusercontent.com/34790748/188905291-cc1f20fb-95e6-4efb-bb8e-cf6eb67097a3.mp4

**Comment by infinite-persistence** [comment]
`--- Draft ---`

The `pref_set` should not happen until Save is pressed.  I'll double-check what's wrong.  
The intended behavior is:
- When one tab changes language, all tabs will change locally from the tab-sync mechanism, but none would write to wallet until Save is pressed.

**Comment by infinite-persistence** [comment]
`--- ready ---`
- Fixed the "toggle back and forth" (really, this time :crossed_fingers:)
- Fixed temporary switch-back to English while logging in (it was waiting for the new language to be fetched, but could have used the already-fetch browser language instead).
- Removed language nag

**Pull request merged**
