### PR TITLE
Remove unused strings

### PR DESCRIPTION
**Pull request by infinite-persistence**
These are from Desktop, commented code, or defunct/unused features.

The list needs to be pruned often to (1) keep the file small (2) reduce unnecessary work for translators, especially when adding new language.

----

The scripted approach captures too much, but it is cool and worth iterating to maybe work together with the `REPORT_NEW_STRINGS` console functionality.

### CODE REVIEW

**Comment by tzarebczan** [comment]
we're still sharing the same app strings as desktop, so should we keep those?

**Comment by infinite-persistence** [comment]
Oh, I thought that after the discussion with Jessop to make Desktop stop sending to Transifex, we're gonna own and drive the file, and they will use something else?

These were already removed since last year, and some aren't present in both repos too.  It's hard to maintain removals from two repos, and probably not good to accumulate unused strings for the reasons above.

But I see your point, so Desktop translations have been broken for a year?  Then again, they haven't been sending new ones, so it's gonna be partial anyways.

**Comment by tzarebczan** [comment]
Don't think that ever happened. Probably fine if they are incomplete there, and fine to remove for now.

**Comment by tzarebczan** [comment]
Still need to add the new string generation process to the build script. It no longer uses lbry.com, but instead they are stored locally on the server.

**Pull request merged**
