### PR TITLE
Updating dependencies, and removing deprecated packages

### PR DESCRIPTION
**Pull request by iamflorencejay**
## Changes
- Updating some of the packages that is not considered a breaking change
- Adding openssl-legacy-provider to support 
- Removing babel/polyfill and adding corejs/stable to the code
- Changing the vast client to @dailymotion/vast-client
- Changing @babel/eslint to @babel/eslint-parser

### CODE REVIEW

**Comment by iamflorencejay** [comment]
Adding some code fot #1191

**Comment by tzarebczan** [comment]
I don't think we'll consider this for now, don't have the bandwidth to upgrade random packages + test various things. The vast client can probably removed in another PR, we're not using that for now. 

Not sure what the openssl legacy is for, and polyfill changes sound rather risky. 

Appreciate the attempt though! Maybe if you want to get 1191 building/passing again on it's own?

**Comment by iamflorencejay** [comment]
Copy that. I've changed it because polyfill is now deprecated, and some of it is deprecated too. @tzarebczan

**Comment by iamflorencejay** [comment]
OpenSSL Legacy is technically to run legacy openssl on newer Node.JS versions. That's about it.

**Comment by iamflorencejay** [comment]
It is recommended by Babel to use corejs/stable now instead of babel/polyfill @tzarebczan so make this a reconsideration

**Comment by iamflorencejay** [comment]
I've also tested it on web-server instance, and it is ay-ok

**Comment by iamflorencejay** [comment]
Currently waiting @tzarebczan

**Pull request closed without merging**
