### PR TITLE
[on hold] Support nodejs 16 - Fix one annoying warning when building

### PR DESCRIPTION
**Pull request by nikooo777**
there are still a couple of deprecation warnings that you might want to look into

```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($COLLAPSED-HEIGHT * 3, 4) or calc($COLLAPSED-HEIGHT * 3 / 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

  ╷
9 │   max-height: $COLLAPSED_HEIGHT * 3 / 4;
  │               ^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
    ../ui/scss/component/_expandable.scss 9:15  @import
    stdin 26:9                                  root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($nudge, 2) or calc($nudge / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
22 │     border-radius: round($nudge / 2);
   │                          ^^^^^^^^^^
   ╵
    stdin 22:26  root stylesheet
```

however it seems to build and run fine locally

### CODE REVIEW

**Comment by infinite-persistence** [comment]
- [ ] Test
- [ ] Update readme to reflect new v16 requirement

**Comment by tzarebczan** [comment]
Will get some more testing this week and get it shipped..

**Comment by iamflorencejay** [comment]
I've done on max height already, prolly border radius next time

**Comment by iamflorencejay** [comment]
I also want to update that darn webpack plugin. Probably on the next release.

**Comment by tzarebczan** [comment]
we'll upgrade to v18 in a new PR.

**Pull request closed without merging**
