### PR TITLE
Warn about potential tier-restriction failure

### PR DESCRIPTION
**Pull request by infinite-persistence**
Please inspect the Engrish :laughing: 

image

image

### CODE REVIEW

**Comment by infinite-persistence** [comment]
Yeah, it's also potentially not needed if the occurrences are low -- better not to highlight something that's not widespread?
No worries if want to drop the PR -- it's up just as a choice when we need it.

**Comment by tzarebczan** [comment]
@mayeaux can we make it so that a file page will alert the creator when the restrictions didn't make it into internal apis. You should see the tag, but member content check fails. 

Then they can easily know.

It's either we do this, or the other idea i had of storing the data on frontend, and then later checking it up against the API at done interval, and removing if found. This would be the best until we can integrate this into the backend. 

I'll do another count of occurrences today.

**Comment by tzarebczan** [comment]
- [ ] also look at the user side who has a membership -  put up a message to check back later.

**Comment by tzarebczan** [comment]
we'll still use this message, but we'll get a self heal process going.

**Comment by tzarebczan** [comment]
I think we can close this with the self healing process now...

**Pull request closed without merging**
