### PR TITLE
Sort collection by release time buttons

### PR DESCRIPTION
**Pull request by keikari**
Allows sorting items in collection by release_time.  

@toshokanneko 
I can't figure out how to make UI stuff. Could you help(make) the UI side? 

This is what my try looks currently. And no idea if scss is done correctly.
scss

EDIT:  Could you also help with lint? I don't really understand what it wants.

### CODE REVIEW

**Comment by toshokanneko** [comment]
I like the idea and the CSS is okay so far, but the actual function of the buttons is not very intuitive. I mean, the icons indicate ascending and descending, but by which value? Title? Date? Length? However, adding a label or another icon could be too much. Not sure what the ideal solution for this would be yet :thinking:

**Comment by keikari** [comment]
What about having some Sort-button in place of arrows? And that opening menu like this with options newest/oldest first. (Saw this on youtube)
button-menu

**Comment by toshokanneko** [comment]
Yeah, that's what I've been thinking about. Basically something like this...maybe with less options though.
image

Also, we should probably add an option that allows you to revert the change...or...to be more specific, we shouldn't save the change immediately. We might wanna add `Save changes` and `Cancel` buttons similar to the ones on the channel edit page. 

Otherwise if you change the order just out of curiosity you can't revert it. My test playlist is still sorted by date just because I pressed that button xD

**Comment by keikari** [comment]
Also was thinking about the instant saving of changes in this. @tzarebczan said it would be fine as is, since public lists at least have a way to revert the changes.  But I think I can make it work like you said, if wanted.   

Would correct way to implement be basically to add something like `unSavedCollections` in redux, in which the changed order would get stored until "Save" or "Cancel" is clicked? (Not storing this to wallet)

**Comment by toshokanneko** [comment]
Jep, exactly :)

**Comment by keikari** [comment]
If implemented properly, it now should have functionality of changes done in arrange mode being temporary until saved.  (Just added some UI buttons to save/cancel for now)

Also while at it made the changes to list items being temporary on edit page until "Save" is clicked.

**Comment by keikari** [comment]
Moving clearing of unsaved changes into the collection edit makes changing order in player side list not break for lists which have unsaved changes. 

But this kind of thing can still happen.
1. Change order of claims
2. Navigate elsewhere on the page without saving or clearing changes
3. Unsaved changes are still in the list, but disappear on page refresh. 
Or would get saved if changing order of claims in the player sidelist/etc.

Does above case matter, or should the unsaved changes  only show on the arrange mode in collection page and in the collection edit page?  Or something else.

**Comment by toshokanneko** [comment]
Looks good functionality wise. I've just noticed that the save & cancel buttons on the channel edit page are no longer fixed. Dunno why and when that broke. Sorry for giving you that as an example. I'll fix that right now. What I meant was something like this with a fixed position. Just to make sure that the user knows that there's a save button even when the list is very long. 
image

**Comment by keikari** [comment]
Wasn't sure what toggling edit off from arrange button should do, so just disabled toggling of from it.

Currently looks like this on desktop (Not super happy with the sort button, don't know where's best placement for it. Any thoughts?):


Not sure what to do on mobile(Any ideas, or good enough for now?):

**Pull request merged**
