### PR TITLE
Add role="application" to main div (web)

### PR DESCRIPTION
**Pull request by jxxp9**
## Fixes

Issue Number:

## PR Checklist

<details><summary>Toggle...</summary>

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

Please check all that apply to this PR using "x":

- [ ] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

</details>

### CODE REVIEW

**Comment by tzarebczan** [comment]
Thanks for the PR. What does this help with and its purpose?

**Comment by jxxp9** [comment]
Accessibility, it signals the screen reader that the div is the application main entry point and it configures it in desktop app mode

**Comment by tzarebczan** [comment]
Thanks for the explanation!

**Comment by tzarebczan** [comment]
There's a user with the NVDA screen reader who says the site is now worse with this setting. 

His feedback:

```Aplication mode is very agrivating with NVDA screen reader... in my experience: I just tried to go to odysee and now the whole page is some sort of application. At first I thought the page was not loading. I use a screen reader to see with. When I load Odysee I use the B key to navigate over to the notifications button first. Now B just says B back to me and the arrow keys do not work. The 1 key would take me to heading level one but now I get ONE said back to me. I can tab one element at a time past things to the notifications button... skip navigation and all but I can not use any feature like Landmarks, headings or objects to navigate any more. And when I try to open the menue I still get logout or change my channel and nothing else?``` 

Going to revert this for now, but feel free to provide more feedback as to what should be happening or if it's something just related to nvda.

**Comment by jxxp9** [comment]
Oh didn't expect this to happen, sorry for the user

**Pull request merged**
