### PR TITLE
updated the transform origin for menus

### PR DESCRIPTION
**Pull request by MaxKotlan**
## Fixes

Issue Number: 

## What is the current behavior?

Currently, menus have their transform origin in the middle so they expand from the center.

menu-old

## What is the new behavior?

This PR sets the transform origin on the top of the menu. 

menu-new

## Other information

Unfortunately, when there isn't enough screen space to display the menu below the target element, the menu will appear on top and it will look like this:
menu-new-badanimation

## Future Enhancement

It would be nice if it was possible set the transform origin on the bottom if the menu is above the target element

That would look like this:
menu-item-bottom-correct

I couldn't figure out an easy way to determine if the menu was above or below the target element, so I jus set the transform origin to the top in all cases. I think this makes sense because according to the [reach ui menu button docs](https://reach.tech/menu-button/#menupopover-position), the menu will always try to position itself below unless there isn't enough screen space. That means in most situations the menu will display below and the transform origin will be correct.

## PR Checklist

<details><summary>Toggle...</summary>

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [x] Other - Please describe: UX Improvement

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I added a line describing my change to CHANGELOG.md
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

</details>

### CODE REVIEW

**Comment by infinite-persistence** [comment]
Note: Xander tried this before and we had to revert later. 
Not sure if this PR's approach is the same, but whoever's reviewing this should probably dig up what broke in Xander's PR and see if it happens with this approach.

**Comment by infinite-persistence** [comment]
Here's Xander's attempt: https://github.com/lbryio/lbry-desktop/pull/5381
Here's the scenario that requires the revert: https://github.com/lbryio/lbry-desktop/pull/5439

**Comment by MaxKotlan** [comment]
@infinite-persistence  Thanks for linking the PR!

It looks like I took a slightly different approach. I didn't modify the animation at all, only the transform origin. I don't think this approach would recreate that error, but I will try to pull the old issue, recreate it, and see if this PR has that issue.

**Comment by infinite-persistence** [comment]
Yup, agree. From a glance, it looks good :+1:

**Comment by MaxKotlan** [comment]
@infinite-persistence 
I think I was able to recreate the old issue. For whatever reason in the old version it would auto click the first item in the menu.
menu-bug-version

In this PR it should work as expected.
version-in-this-pr

**Comment by tzarebczan** [comment]
Thanks for the contribution @MaxKotlan, appreciate it! Shoot me an email at tom@odysee.com so we can get some credits over to you for the help and maybe see if you're interested in contributing more :)

**Comment by infinite-persistence** [comment]
@MaxKotlan, do you think it's possible to animate from down-to-up when necessary?  Currently, if the button is near the bottom edge, the popup still flows from top-to-bottom.

Don't worry about it if there's no simple fix.

image

**Comment by MaxKotlan** [comment]
@infinite-persistence I think it is possible, but it would require a bit of effort.

We would have to figure out how to hook into this position property on the menu/popover.
https://reach.tech/menu-button#menupopover-position

If we can do that, all we have to do is swap out a css class to change the transform origin.

We would probably have to update all the menus individually, or create a wrapper component and update all the menus to use the wrapper component.

**Comment by infinite-persistence** [comment]
Thanks for checking :+1: .  Yeah, probably not worth the effort for now.

**Pull request merged**
