### PR TITLE
Make notification titles translatable

### PR DESCRIPTION
**Pull request by infinite-persistence**
## Issue
Desktop 7022: i18n: Notification title localization lost

## Approach
The current code breaks up the string into an array of strings, so i18n is somewhat impossible.

Since 99%¹ of dynamic notifications come with a `dynamic` property for all the replaceable values, we can actually reconstruct the string however we want.

¹ <sub>_as far as I can find, only `fiat_tip` does not provide the value via `dynamic`, i.e. hardcoded in the string. Boo._</sub>

### Benefits of this approach:
- able to localize the string again
- able to customize the string (e.g. making claim titles italic, fix typos, use more concise strings, etc.)

### Problems with this approach:
- if the api overloads a particular notification type with several strings, then the approach is broken.
    - Ex. For the case of `comment` type, the overload is whether the comment is a normal comment or hyperchat. But I was able to replicate the logic to differentiate them, so all is good.
    - For the case of "livestream reminder in 30 minutes", we would have to inspect the string to differentiate against "is live streaming". I think this reminder is not being used, so I didn't do it yet.
- some work is needed to maintain the code when the server side updates something.  But we are already manually maintaining the i18n strings anyway, so it shouldn't be too much of a burden.
- With the exception of the overload problem, any new notification type will simply pass through as un-localized, so things should continue to work, i.e. no need to update the front-end immediately 🤞

### CODE REVIEW

**Comment by tzarebczan** [comment]
Another downside to not doing it in internal apis is that push notifications won't be localized. But this is probably better until we can get localization on there. 

Cc @tiger5226

**Comment by infinite-persistence** [comment]
Do we still want this?  I'll resolve the conflict if so.

I'd argue there's no harm doing it, since:
- It's unlikely internal-api support will come anytime soon, given other larger features.
- Solution is self-contained in a file -- can swap or throw away easily.
- Not leaving patches of English text in non-English mode as much as possible (all well known sites have 100% i18n coverage).

**Comment by tzarebczan** [comment]
Yes, let's just do it...you're absolutely right.

**Comment by infinite-persistence** [comment]
[7cfe2b4 ](https://github.com/OdyseeTeam/odysee-frontend/commit/7cfe2b46b68798ea4c888fe8748763264f96ef82)to [523bc87 ](https://github.com/OdyseeTeam/odysee-frontend/commit/523bc875d566d2d18c2f0d627e1f9ebb0faebdac)
- Rebased
- Add styling
- Test: `kp`

**Pull request merged**
