### PR TITLE
Adjust meta data to allow search pages to reflect search term

### PR DESCRIPTION
**Pull request by david0178418**
resolves https://github.com/OdyseeTeam/odysee-frontend/issues/25

## What is the current behavior?

Currently, the search page metadata is the default values.

## What is the new behavior?

The search page metadata renders as:

Title: %term% Search Results
Description: Find the best %term% content on %site_name%

image
image

## Other information

Considering the metadata is currently static and the request requires dynamic content, I modified the "category-metadata" object to return a function that can optionally take in the query params which returns the expected object. 

## PR Checklist

<details><summary>Toggle...</summary>

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I added a line describing my change to CHANGELOG.md
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

</details>

### CODE REVIEW

**Comment by tzarebczan** [comment]
Needs a small conflict fix from adding a new category, but let's review to make sure the approach is right.

**Review by infinite-persistence — COMMENTED** [review]
Looks good.

Few thoughts:
- Maybe a need an image in the future.
- `og:url` points to `https://odysee.com/$/search`.  This link (without param) current crashes in production.
- Not sure if we need to handle an empty string for `q` or not in the future.  Might end up `Find the best "" content on Odysee`.

**Comment by david0178418** [comment]
@infinite-persistence , good call.

image

Additionally, the empty string case, is now handled:
image

Also, validated that the existing categories still work as expeted:
image

I did a double check, but just to confirm, the search crash is a preexisting issue, correct?

Also, just a heads-up that I'll be able to respond to any additional notes you may have later this evening.  I'll be out and and about for a good chunk of the day.

**Comment by tzarebczan** [comment]
Thanks @david0178418.

Most people would share this from their browser, so it would have query params.

**Pull request merged**
