### PR TITLE
Use comma or period button to step a frame forward or backward

### PR DESCRIPTION
**Pull request by mayeaux**
Allows a user to skip forward or backwards a frame using either the comma or period keyboard shortcut.

Offered by YouTube, part of moving closer to YouTube feature parity

https://support.google.com/youtube/answer/7631406?hl=en

### CODE REVIEW

**Comment by mayeaux** [comment]
Works well for me but could use some testing and some sanity testing of the client-side implementation of FPS calculation (works accurately and doesn't seem to have much overhead but could use a second set of eyes)

**Comment by infinite-persistence** [comment]
Didn't evaluate performance, but:
- [ ] Calculation runs every time you toggle play/pause.  Probably don't need to recalculate each time?
- [ ] Calculation runs every time you seek while it's playing.
- [ ] On livestream, calculation runs every time the livestream buffers.
- [ ] The shortcut should probably not be active while it's playing. YT only allows it when paused.
- [ ] Maybe don't need to register in mobile, where it's hard to even invoke the keyboard?  (or maybe it's already not registered)

**Comment by mayeaux** [comment]
>Maybe don't need to register in mobile, where it's hard to even invoke the keyboard? (or maybe it's already not registered)
It's linked up the same way the rest of the current keyboard shortcuts are, so my assumption is that they aren't accessible on mobile, but I can investigate making sure they don't run on mobile if we consider that to be a priority, I'm not aware of any issues with the current implementation

**Comment by infinite-persistence** [comment]
The idea was to skip the estimate calculation on battery-powered devices entirely since the feature cannot be accessed anyway (or at least I couldn't figure out how).  

e.g. On Android Firefox, I see no way to invoke the keyboard + make the video element in focus.  The keyboard only appears in comments or address bar.

**Pull request merged**
