### PR TITLE
Claim filter: add ability to define custom Duration  

### LINKED ISSUE #1801: Allow setting custom duration option on duration picker
On channel pages, and other areas where we have the duration picker, give an option to set a custom duration (in minutes?), that can be used. Once added, it should persist until changed if possible/easy (doesn't have to be for this release).

### PR DESCRIPTION
**Pull request by infinite-persistence**
- Closes #1801
- Test: `kp`
- Rave mentioned he will re-do the filter UI as a whole later (although it doesn't look that bad as-is, except for the checkbox that looks out of theme).
- Details:  see commit messages

### CODE REVIEW

**Comment by tzarebczan** [comment]
Awesome, will check this out some more! Some quick feedback

- "Longer than", "shorter than" vs greater/less. 

- maybe it should say "custom", and then you get shorter/longer than. The 2 entries on their own seem a bit strange at first, as I don't know what will happen and that it's customizable. Maybe there's better ways to present, we can explore later. 

- is it easy to add the filter to following page too? 

- little loading icon when you change value to show that it's updating?

**Comment by infinite-persistence** [comment]
> _maybe it should say "custom", and then you get shorter/longer than. The 2 entries on their own seem a bit strange at first, as I don't know what will happen and that it's customizable. Maybe there's better ways to present, we can explore later._

Did that initially, but I agree with Rave on simplifying to just 2 components. Anyway, will try out both with some hang time to see which is nicer.

**Comment by infinite-persistence** [comment]
- [b71129c ](https://github.com/OdyseeTeam/odysee-frontend/commit/b71129c4f12c0268e9120e9d36d463a58c400aec)to [95f2861 ](https://github.com/OdyseeTeam/odysee-frontend/commit/95f2861d0aeccb0b7106c2d21302cae52bee55a2)
  - Fixed phrases.
  - Enabled advanced filter in Following Page (might need a second look)

**Comment by tzarebczan** [comment]
Awesome! I'll file a fall out issue for the styling pass,etc.

**Pull request merged**
