### PR TITLE
ClaimListHeader: Restore tag filter + enter query directly

### LINKED ISSUE #1371: Add tag filter / search + sorting options to wild west
We used to have a tag filter on the old discover page. Would be great to bring that back, and maybe add an option to fill in own tag term to filter on.

Also add the new/top/trending sort, default trending as usual.

### PR DESCRIPTION
**Pull request by infinite-persistence**
Closes #1371 
.

### CODE REVIEW

**Comment by tzarebczan** [comment]
- [ ] Most users won't have followed tags - maybe "followed tags" option will be confusing? Hide it if no tags followed? 
- [ ] remove "The tags you follow will change what's trending for you. " on manage page
- [ ] Maybe incorporate manage tags UI (slimmed down version) into manage following? Or at least hyperlink manage tags?

**Comment by infinite-persistence** [comment]
> _Maybe incorporate manage tags UI (slimmed down version) into manage following?_

You mean roughly something like this?



> _Or at least hyperlink manage tags?_

The "Manage" button?  It should be a hyperlink already.

**Comment by tzarebczan** [comment]
Scratch most of my feedback. After talking to drew, he thinks this search be custom filter only option, and available on the top right hand side of the pages. 

So pretty much this, with "Tag search:" label 
image
image

That will simplify it a bit also. Sorry for making you do the other work, hopefully it was mostly resurrecting stuff. 

Mobile UI for that may be trickier...

**Comment by infinite-persistence** [comment]
## [28d4549 ](https://github.com/OdyseeTeam/odysee-frontend/commit/28d4549357bf0ae850e91c36cd1854f95d9b6903)to [744a34e ](https://github.com/OdyseeTeam/odysee-frontend/commit/744a34ed1758bf008f1784bbf3e81aca3d262f86)
- Version 2
- I placed it somewhere else instead of the right side due to various reasons.  Check it out in dev instance -- I think it makes more sense and reflows in mobile.
- Just like before, it is enabled everywhere the filter component is used (why not, feels useful).

**Comment by tzarebczan** [comment]
Looks great to me, just having Drew take a peek!

**Comment by tzarebczan** [comment]
Drew said he wants the input box available by default, no way to toggle. So maybe do that for desktop, but toggle on mobile to save space?

**Comment by infinite-persistence** [comment]
- Expand search bar on page entry for Large layout.
- Fix input field not populated with the query string on F5 (although the payload sent was correct).
- Styling:
    - Fix hover and active style to match adjacent buttons.
    - Fix placeholder size to match the placeholder size for the channel-search widget.
    - Re-do css to make obvious which selectors we are overriding.

**Comment by tzarebczan** [comment]
@infinite-persistence please fix small conflict and we'll ship, thanks for getting the changes done!

**Pull request merged**
