### PR TITLE
Notification Menu Upgrade

### PR DESCRIPTION
**Pull request by toshokanneko**
- ~Mark notifications in dropdown as seen on hover.~
- Increase dot size
- Mark all notifications as seen on button click

### CODE REVIEW

**Comment by toshokanneko** [comment]
Not yet if at all. One of the reasons why I've decided to add this functionality was to give the users an easy option reduce the counter number. Both the border on the left and the small dot used to indicate an unread entry. Now the dot is used for the unseen ones and if you just quickly scroll through the list you can mark all of them (or at least the latest 20) as seen. I think this should "solve" the issue in most cases. You can still mark all notifications as seen by going to the notification page and there you can mark all as read by using the button.

**Comment by tzarebczan** [comment]
Clicking the notification button at all should probably just mark all as seen to clear out the count - that's how a few other sites do it. Then everything else can just be marking read or not. Thoughts? 

If not, there still should be an easier way to clear that count without having to scroll or click view all to navigate away.

**Comment by toshokanneko** [comment]
Sounds fine to me.

**Comment by tzarebczan** [comment]
Looking good! 

Still think people may want a mark all as read - maybe we can find another way to incorporate it. 

FB has it in a menu option:
image

**Comment by toshokanneko** [comment]
Yeah I know. I got rid of that top border in my latest branch because I moved the entire menu to the right and it looked weird there. That's why I've decided not to add another button there...and at the bottom it would look kinda bitty. I'll try to find a better solution.

**Pull request merged**
