### PR TITLE
Video-player settings menu

### PR DESCRIPTION
**Pull request by infinite-persistence**
## Ticket
Closes [#1394 Video: Allow access to all controls in small screen](https://github.com/OdyseeTeam/odysee-frontend/issues/1394)

Test:  `kp`  -- If approved, assign back to me.

- This PR paves the infrastructure to move items into the menu + also moved a few as an example.
- I dropped the idea of dynamically placing the button on the bar vs. in menu depending on available space.  Seems to kill muscle memory, and I think UI button location shouldn't move too much?

## Known issues (<strike>will fix</strike> fixed)

<details>
  <summary>expand :small_red_triangle_down: </summary>

- [x] The popup should be dismissed when the control bar is dismissed-on-idle.
- [x] <strike>Color [is off](https://user-images.githubusercontent.com/64950861/228461451-f8ec6fd0-6995-4b70-9f9f-00fe2e4d7307.png) in the dev instance.  Works ok in localhost.</strike>  `--fixed--`
- [x] <strike>I missed out Theater Mode.</strike>  `--skip--` Won't do. Doesn't make sense because this causes the popup to move drastically, which is bad UI
- [x] Localization.

</details>

## Postponed

- [ ] The popup looks the same for both Mobile and Desktop for now.  I think all popups in mobile should eventually be done as a modal, like how combo-boxes are natively on mobile.
- [ ] Move Quality Selector into the menu.

## Lobbying some theme changes
@toshokanneko, fyi:

<details>
  <summary>expand :small_red_triangle_down: </summary>

- Can we change the popup selection hover color to something beside red?  Reasons:
    1. Having the same color for both "selected" and "hovered" has been confusing.  [Example](https://user-images.githubusercontent.com/64950861/228456370-d329c7b9-2fa7-4efa-8ad7-20e599c54628.png).  
    2. More importantly, since we can have toggle buttons now (also red), it doesn't look good unless we do some shadowing.   Picking gray seems like the easiest?
        - image
- For popups in the video player, can we just use the dark theme only?  Seems to blend better with dynamic video background.

</details>

### CODE REVIEW

**Comment by infinite-persistence** [comment]
`--- draft ---`
Set to draft to fix remaining issues, but it remains testable.

**Comment by infinite-persistence** [comment]
- Fixed color issue

**Comment by tzarebczan** [comment]
Tried it quickly - switching rate doesn't take effect, and it stays on the same rate.

**Comment by infinite-persistence** [comment]
What's the video to reproduce?  Seems ok here:

https://user-images.githubusercontent.com/64950861/228622284-3a963665-9d0f-4898-b41c-44f68aa6edd0.mp4

**Comment by tzarebczan** [comment]
seems to be working now, not sure what happened there..I had tried multiple videos. Will try to repro.

**Comment by tzarebczan** [comment]
ah - try it on a livestream - doesn't work there, and then it doesn't work with any other videos after (without a refresh)

**Comment by tzarebczan** [comment]
Never liked the idea of manual dispose, unless it would solve some real problems. 

I think for livestreams its supposed to default to 1x once it catches up to live edge. If it's broken, don't need to fix it now, we can file.

**Comment by keikari** [comment]
* [ ] Menu opens at very right on embeds
embed

----------------------

I think speed settings would be better in descending order

**Comment by infinite-persistence** [comment]
- Fixed popup location on embeds
- Changed playback-rate order to descending
- Consolidated menu-item sorting code into 1 place.

**Comment by infinite-persistence** [comment]
@toshokanneko, rebased -- no clashes as expected.
Let me know what you think of the new styling.  If you want to change directly in the branch, that's fine too.

**Comment by toshokanneko** [comment]
Rebased version looks based :+1:

**Pull request merged**
