### PR TITLE
Announcements framework

### PR DESCRIPTION
**Pull request by infinite-persistence**
Ticket:  Closes [#1454 Framework for features updates / announcements ](https://github.com/OdyseeTeam/odysee-frontend/issues/1454)

## How it works
1. Display announcement through a modal at startup:
  - image
  - It will only be shown once per entry.
  - Users can manually re-open it to review from `Settings > Help > What's New`.
    - image
2. Content definition is through markdown. 
  - It's currently hardcoded in the component file, but I envision it to be part of homepage `{ categories, meme, announcement }`.  But it can be from wherever we want.
  - I'm thinking it should per-homepage rather than per-language, since translating to all languages in time would not be feasible.
  - Content length can be infinite (content area will be scrollable).

## Style Todo (but not needed for MVP)
- [ ] Animate the modal's appearance.
- [ ] Mobile modals will take over the full screen.  I think for the case of announcement, it should just take parts of the screen, so that returning or first-time users know it's a modal.

## Dev/Testing notes
- <strike>Delete `viewed-announcement-hash` in local storage to make the same text appear at startup.</strike>

### CODE REVIEW

**Comment by tzarebczan** [comment]
This is awesome! Agree on it being in homepages, but can start here. I haven't had a chance to check it out, sorry. 

Other thoughts:
- probably don't want it for new users? 
- Is it only on homepage (probably what we want)

**Comment by infinite-persistence** [comment]
[d030e51 ](https://github.com/OdyseeTeam/odysee-frontend/commit/d030e51815c4a9ecdad139877150f2dff055d46e)to [40f808e ](https://github.com/OdyseeTeam/odysee-frontend/commit/40f808e955f6080d0a531f397d72cbafc7851e3b)
- Exclude incognito and only show if loaded from the homepage.

**Comment by infinite-persistence** [comment]
After putting it up on a dev instance, I realized it won't work when re-opening the browser because the local cached version is used (same issue as "users stuck with old version").

Will need #1329 so that an explicit F5 is not required.

**Comment by infinite-persistence** [comment]
Fastest solution to the issue above is to continue with built-in homepage + fetch v2 but only use the `announcements` data.

**Comment by tzarebczan** [comment]
I'm ok with V2 for announcement data

**Comment by tzarebczan** [comment]
Worth syncing to wallet also? So let's say i sign in on another device or log out / back in, i don't see it again?

**Comment by infinite-persistence** [comment]
## Moved storage to wallet
It opened up more timing corner-cases, but I think I covered it all.  Asking Miko to try out would be nice.

Note that moving to the wallet means we need to wait until the first sync before announcements can appear -- can be up to 5 seconds.

Testing notes:
- Moved to `inf` test instance.
- Use `window.clearLastViewedAnnouncement()` to reset.  Wait until "populating..." appears.
- Ideas for permutation:  Refreshing and logging in are 2 different redux paths (wallet vs rehydrate).

**Comment by infinite-persistence** [comment]
[523c037 ](https://github.com/OdyseeTeam/odysee-frontend/commit/523c037e9e10765c4b5da6c0f1b69207d5574df2)to [14a11aa ](https://github.com/OdyseeTeam/odysee-frontend/commit/14a11aa78a356241c5c15a1bfbc3c6cfe7013db4)
- Don't show "What's New" button in Help Page if no announcements.
- Need to trim the value as an empty file is `\n` and would still invoke the modal.
- Test several rounds of actual updates and builds cycles.

**Pull request merged**
